extend type Mutation {
    "Register a new customer account"
    register(input: RegisterInput! @spread): RegisterResponse!
        @validator(class: "App\\Modules\\Api\\GraphQL\\Validators\\RegisterInputValidator")
        @field(resolver: "App\\Modules\\Api\\GraphQL\\Mutations\\AuthMutation@register")
}

"Input structure for the register mutation"
input RegisterInput {
    name: String!
    email: String!
    password: String!
    password_confirmation: String!
}

"Response structure returned by the server"
type RegisterResponse {
    status: Boolean!
    message: String!
    user: User
}
