"A datetime string with format `Y-m-d H:i:s`."
scalar DateTime
    @scalar(class: "Nuwave\\Lighthouse\\Schema\\Types\\Scalars\\DateTime")

type Query {
    user(
        id: ID @eq @rules(apply: ["prohibits:email", "required_without:email"])
        email: String
            @eq
            @rules(apply: ["prohibits:id", "required_without:id", "email"])
    ): User @find(model: "App\\Core\\Models\\User")

    users(name: String @where(operator: "like")): [User!]!
        @paginate(model: "App\\Core\\Models\\User", defaultCount: 10)
}

type User {
    id: ID!
    full_name: String!
    email: String!
    status: String!
    roles: [Role!]! @belongsToMany
    created_at: DateTime!
    updated_at: DateTime!
}

type Role {
    id: ID!
    name: String!
    description: String
    created_at: DateTime!
    updated_at: DateTime!
}

type AuthPayload {
    status: Boolean!
    message: String!
    access_token: String
    token_type: String
    expires_in: Int
    user: User
}

type LogoutResponse {
    status: Boolean!
    message: String!
}

type Mutation {
    login(email: String!, password: String!): AuthPayload
        @field(
            resolver: "App\\Modules\\Admin\\GraphQL\\Mutations\\AdminAuthMutation@login"
        )

    logout: LogoutResponse
        @field(
            resolver: "App\\Modules\\Admin\\GraphQL\\Mutations\\AdminAuthMutation@logout"
        )
}
